# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FWPopupView' do
  
  # 布局：https://github.com/SnapKit/SnapKit
  pod 'SnapKit'
  
  # IQKeyboardManagerSwift：https://github.com/hackiftekhar/IQKeyboardManager
  pod 'IQKeyboardManagerSwift'

end
